-- Question 1
-- VI
SELECT FNAME, LNAME, JOBID, X.DEPTID
FROM EMP AS X, DEPT AS Y
WHERE X.DEPTID = Y.DEPTID
AND Y.DEPTNAME = 'Finance'
;
-- XIII
SELECT *
FROM EMP
WHERE EMPID IN (137, 159, 183)
;
-- X
SELECT *
FROM EMP
WHERE COMMISSION
BETWEEN (
    SELECT MIN(COMMISSION)
    FROM EMP
)
AND 2500
;
-- XI
SELECT *
FROM EMP
WHERE DEPTID
NOT IN (
    SELECT DEPTID
    FROM EMP
    WHERE MANID
    BETWEEN 100 AND 250
)
;
-- XII
SELECT *
FROM EMP
WHERE JOBID = (
    SELECT JOBID
    FROM EMP
    WHERE COMMISSION = (
        SELECT MAX(COMMISSION)
        FROM EMP
        WHERE COMMISSSION
        BETWEEN 0
        AND (
            SELECT MAX(COMMISSION)
            FROM EMP
        ) - 1
    )
)
;
-- XIII
SELECT FNAME, LNAME, HIREDATE
FROM EMP
WHERE DEPTID = (
    SELECT DEPTID
    FROM EMP
    WHERE FNAME = 'Clara'
)
AND FNAME <> 'Clara'
;
-- XIV
SELECT EMPID, FNAME, LNAME
FROM EMP
WHERE DEPTID IN (
    SELECT DEPTID
    FROM EMP
    WHERE FNAME LIKE '%t%'
    OR LNAME LIKE '%t%'
)
;
-- XV
SELECT EMPID, FNAME, LNAME, COMMISSION
FROM EMP
WHERE COMMISSION > (
    SELECT AVG(COMMISSION)
    FROM EMP
)
AND DEPTID IN (
    SELECT DEPTID
    FROM EMP
    WHERE FNAME LIKE '%j%'
    OR LNAME LIKE '%j%'
)
;
-- XVIII
SELECT EMPID, FNAME, LNAME, JOBID
FROM EMP
WHERE COMMISSION < ANY (
    SELECT COMMISSION
    FROM EMP
    WHERE JOBID = "IT_PROG"
)
AND JOBID <> "IT_PROG"
;
-- XIX
SELECT EMPID, FNAME, LNAME, JOBID
FROM EMP
WHERE COMMISSION > ALL (
    SELECT COMMISSION
    FROM EMP
    WHERE JOBID = "IT_PROG"
)
AND JOBID <> "IT_PROG"
;
-- XXI
SELECT DISTINCT *
FROM EMP
WHERE COMMISSION = (
    SELECT MIN(COMMISSION)
    FROM EMP
    WHERE COMMISSION BETWEEN (
        SELECT MIN(COMMISSION)
        FROM EMP
    ) + 1
    AND (
        SELECT MAX(COMMISSION)
        FROM EMP
    )
)
;
-- XXII
SELECT CITY
FROM LOCA
WHERE LOCID = (
    SELECT LOCID
    FROM DEPT
    WHERE DEPTID = (
        SELECT DEPTID
        FROM EMP
        WHERE EMPID = 134
    )
)
;
-- XXIV
SELECT FNAME, LNAME, COMMISSION, DEPTID
FROM EMP
WHERE COMMISSION > (
    SELECT AVG(COMMISSION)
    FROM EMP
)
ORDER BY COMMISSION DESC
;
-- XXVI
SELECT FNAME, LNAME
FROM EMP AS X
WHERE X.COMMISSION > 0.5*(
    SELECT SUM(Y.COMMISSION)
    FROM EMP AS Y
    WHERE X.DEPTID = Y.DEPTID
)
;
-- XXVIII
SELECT FNAME, LNAME, COMMISSION, DEPTNAME
FROM EMP, DEPT
WHERE EXISTS (
    SELECT *
    FROM EMP
    WHERE COMMISSION > 3700
    AND EMP.DEPTID = DEPT.DEPTID
)
;
-- XXIX
SELECT DEPTID, DEPTNAME
FROM DEPT
WHERE NOT EXISTS (
    SELECT *
    FROM EMP
    WHERE EMP.DEPTID = DEPT.DEPTID
)
;
