-- Question 1
-- II
CREATE VIEW Q2 AS
SELECT S.BILLNO, S.DATE, S.CUSTID, S.ITEMID, S.QTY, S.QTY*I.PRICE AS AMOUNT
FROM SALE AS S, ITEM AS I
WHERE S.ITEMID = I.ITEMID
;
SELECT * FROM Q2
;
-- III
CREATE VIEW Q3 AS
SELECT *
FROM SALE
WHERE DATE
BETWEEN '2021-09-02'
AND '2022-09-09'
;
SELECT * FROM Q3
;
-- IV
SELECT *
FROM (
    SELECT I.ITEMNAME, I.PRICE*S.QTY AS AMOUNT
    FROM ITEM AS I, SALE AS S
    WHERE S.ITEMID = I.ITEMID
    AND YEAR(S.DATE) = 2021
    ORDER BY AMOUNT DESC
) AS Q4
LIMIT 5
;
-- V
SELECT GROUP_NAME, COUNT(*) AS COUNT
FROM (
    SELECT CUSTID,
    CASE
    WHEN AMOUNT < 10000
        THEN 'SILVER'
    WHEN AMOUNT BETWEEN 10001 AND 50001
        THEN 'GOLD'
    WHEN AMOUNT > 50000
        THEN 'PLATINUM'
    END
    AS GROUP_NAME
    FROM (
        SELECT SUM(QTY*PRICE) AS AMOUNT, CUSTID
        FROM ITEM
        INNER JOIN SALE
        ON ITEM.ITEMID = SALE.ITEMID
        WHERE YEAR(DATE) = 2021
        GROUP BY CUSTID
    ) AS _
) AS _
GROUP BY GROUP_NAME
;
-- VI
WITH TEMP(CUSTID, AMOUNT) AS (
    SELECT CUSTID, SUM(QTY*PRICE) AS AMOUNT
    FROM ITEM
    INNER JOIN SALE
    ON ITEM.ITEMID = SALE.ITEMID
    WHERE YEAR(DATE) = 2021
    GROUP BY CUSTID
)
SELECT X.CUSTNAME, AMOUNT
FROM CUST AS X, TEMP
WHERE X.CUSTID = TEMP.CUSTID
ORDER BY AMOUNT DESC
LIMIT 5
;
