-- Question 1
-- I
CREATE TABLE EMP (
    EMPNO INT(6),
    EFNAME VARCHAR(20),
    ELNAME VARCHAR(20),
    JOB VARCHAR(20),
    DEPTNAME VARCHAR(10),
    DEPTNO INT(2),
    ECITY VARCHAR(10),
    SAL FLOAT(7,2),
    WORKEXP INT(10),
    MANAGERNAME VARCHAR(10),
    MANAGERNO INT(20),
    PRIMARY KEY (EMPNO),
    FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);
-- III
SELECT DISTINCT(OB), LOC
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND EMP.DEPTNO = 80
;
-- V
SELECT ELNAME, DEPTNAME
FROM EMP
WHERE ELNAME LIKE '%a%'
;
-- IX
SELECT ELNAME, DEPTNO, DEPTNAME
FROM EMP
WHERE DEPTNAME = (
    SELECT DEPTNAME
    FROM EMP
    WHERE EFNAME = 'King'
)
;
-- X
SELECT SUM(SAL) AS SUM, AVG(SAL) AS AVG
FROM EMP
;
-- XI
SELECT EMPNO, EFNAME
FROM EMP
WHERE WORKEXP = (
    SELECT MAX(WORKEXP)
    FROM EMP
)
;
-- XII
SELECT COUNT(*)
FROM EMP
;

-- Question 2
-- I
SELECT *
FROM STUDENT
NATURAL INNER JOIN STUDENTCOURSE
;
-- II
SELECT *
FROM STUDENT
NATURAL OUTER JOIN STUDENTCOURSE
;
-- III
SELECT *
FROM STUDENT
NATURAL RIGHT OUTER JOIN STUDENTCOURSE
;
-- IV
SELECT *
FROM STUDENT
FULL JOIN STUDENTCOURSE
;
