-- Question 1
CREATE TABLE COUSE (
    COURSEID INT(20),
    COURSENAME VARCHAR(20),
    PRIMARY KEY (COURSEID)
)
;
CREATE TABLE SECTION (
    TERM VARCHAR(20),
    SECTIONNUM INT(20),
    COURSEID INT(20),
    PRIMARY KEY(TERM, SECTIONNUM, COURSEID),
    FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSEID)
)
;
CREATE TABLE PROF (
    PROFNAME VARCHAR(20),
    PROFNAME VARCHAR(20),
    PRIMARY KEY(PROFNUM)
)
;
CREATE TABLE STUDENT (
    GPA INT(20),
    NAME VARCHAR(20),
    STUDNUM INT(20),
    PRIMARY KEY(STUDNUM)
)
;
CREATE TABLE ENROLLEDIN (
    MARK INT(20),
    STUDNUM INT(20),
    SECTIONNUM INT(20),
    TERM VARCHAR(20),
    PRIMARY KEY(STUDNUM, SECTIONNUM, TERM),
)
;

-- Question 2
CREATE TRIGGER AvailableQuantity
AFTER
INSERT
ON ITEM
FOR EACH ROW
UPDATE PRODUCT
SET STOCK = STOCK - NEW.QTY
WHERE PRODUCT.BARCODE = NEW.BARCODE
;

-- Question 3
CREATE TABLE EMP (
    EMPNO INT(10),
    NAME VARCHAR(20),
    JOB VARCHAR(20),
    MANID INT(20),
    SAL INT(20),
    PRIMARY KEY(EMPNO),
    FOREIGN KEY(MANID) REFERENCES EMP(EMPNO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
;
CREATE TABLE COMPANY (
    EMPNO INT(20),
    NUMBER INT(20),
    DATE DATE,
    PRIMARY KEY(EMPNO),
    FOREIGN KEY(EMPNO) REFERENCES EMP(EMPNO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY(NUMBER) REFERENCES DEPT(NUMBER)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
;
INSERT INTO DEPT VALUES
(1, 'A'),
(2, 'B'),
(3, 'C')
;
INSERT INTO COMPANY VALUES
(1, 1, '1990-09-09'),
(2, 2, '1990-09-09'),
(3, 3, '1990-09-09')
;
DELETE FROM EMP
WHERE EMPNO = 3
;
